[package]
name = "treefuncs"
version = "0.1.0"
authors = ["Cathal Garvey <cathalgarvey@cathalgarvey.me>"]

[lib]
crate-type = ["cdylib"]

[dependencies.cpython]
version = "0.1"
features = ["extension-module"]
